# -*- coding: utf-8 -*-
"""iPhone Sales Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HhcAQpKlv_qSddsvDnuvlDkYARNGaVKc
"""

import numpy as num
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

data = pd.read_csv('apple_products.csv')
data.head()

"""Top 10 highest rated iPhones"""

# first we have to sort ratings of phones from higher to lower:

highest_rated = data.sort_values(by = ['Star Rating'], ascending= False)
highest_rated = highest_rated.head(10)

highest_rated['Product Name']

"""Number of ratings of the top 10 highest rated iPhones"""

label = highest_rated['Product Name'].value_counts().index
highest = highest_rated['Number Of Ratings']

fig = px.bar(highest_rated, x=label, y=highest, title = 'Number of ratings of top 10 iPhones')
fig.show()

"""iPhone with highest number of reviews"""

label = highest_rated['Product Name'].value_counts().index
count = highest_rated['Number Of Reviews']

fig = px.bar(highest_rated, x=label, y=count, title='Number of iPhones with highest ratings')
fig.show()

"""Relationship between sale price of iPhones and number of ratings"""

fig = px.scatter(data_frame = data, x='Number Of Ratings', y='Sale Price', size='Discount Percentage', trendline='ols',
                 title = 'Relationship between Sale price and Number of Ratings')
fig.show()

"""Relationship between Discount percentage and Number of Ratings"""

fig = px.scatter(data_frame = data, x='Number Of Ratings', y='Discount Percentage', size='Sale Price', trendline='ols')
fig.show()

"""Most expensive and least expensive iPhones"""

most_expensive = data.loc[data['Sale Price'].idxmax()]
least_expensive = data.loc[data['Sale Price'].idxmin()]
print('Most expensive Product:')
print(most_expensive)
print('Least expensive Product:')
print(least_expensive)